### PR TITLE
fix(indexing): do not access index before it is ready / while in dumb mode

### PR DESCRIPTION
**Pull request by jankal**
Fix for #231

### CODE REVIEW

**Comment by shyim** [comment]
Thanks! :)

**Comment by shyim** [comment]
Did it build and started for you?

```
2024-11-23T09:51:09 [main] INFO  verification - Finished 1 of 1 verifications (in 21.7 s): IU-243.22562.13 against de.shyim.shopware6:0.0.46: 1 missing mandatory dependency. 1 possible compatibility problem, some of which may be caused by absence of dependency in the target IDE IU-243.22562.13. 12 usages of deprecated API. 36 usages of experimental API
Plugin de.shyim.shopware6:0.0.46 against IU-243.22562.13: 1 missing mandatory dependency. 1 possible compatibility problem, some of which may be caused by absence of dependency in the target IDE IU-243.22562.13. 12 usages of deprecated API. 36 usages of experimental API
Missing dependencies: 
    fr.adrienbrault.idea.symfony2plugin: Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter [202211] and the plugin version [2024.1.276] should have a matching beginning. For example, release version '20201' should match plugin version 2020.1.1
Compatibility problems (1): 
    #Package 'fr' is not found
        Package 'fr' is not found along with its 10 classes.
        Probably the package 'fr' belongs to a library or dependency that is not resolved by the checker.
        It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to **NoSuchClassError**.
        The following classes of 'fr' are not resolved (only 5 most used classes are shown, 5 hidden):
          Class fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher.CallToSignature is referenced in
            de.shyim.shopware6.util.PHPPattern.<clinit>() : void
            de.shyim.shopware6.util.PHPPattern.FEATURE_FLAG_SIGNATURES : MethodMatcher.CallToSignature[]
            de.shyim.shopware6.util.PHPPattern.SHOPWARE_CORE_CRITERIA_ADD_AGGREGATION : MethodMatcher.CallToSignature[]
            de.shyim.shopware6.util.PHPPattern.SHOPWARE_CORE_CRITERIA_ADD_FIELDS : MethodMatcher.CallToSignature[]
            de.shyim.shopware6.util.PHPPattern.SHOPWARE_CORE_SYSTEM_CONFIG_SERVICE_GET_DOMAIN : MethodMatcher.CallToSignature[]
            de.shyim.shopware6.util.PHPPattern.SHOPWARE_CORE_SYSTEM_CONFIG_SERVICE_GET_SINGLE : MethodMatcher.CallToSignature[]
            de.shyim.shopware6.util.PHPPattern.SHOPWARE_STOREFRONT_CONTROLLER_TRANS_SIGNATURES : MethodMatcher.CallToSignature[]
          Class fr.adrienbrault.idea.symfony2plugin.util.MethodMatcher is referenced in
            de.shyim.shopware6.util.PHPPattern.isFeatureFlagFunction(PsiElement element) : boolean
            de.shyim.shopware6.util.PHPPattern.isShopwareCoreSystemConfigServiceGetDomain(PsiElement element) : boolean
            de.shyim.shopware6.util.PHPPattern.isShopwareCoreSystemConfigServiceGetSingle(PsiElement element) : boolean
            de.shyim.shopware6.util.PHPPattern.isShopwareCriteriaAddAggregation(PsiElement element) : boolean
            de.shyim.shopware6.util.PHPPattern.isShopwareCriteriaAddFields(PsiElement element) : boolean
            de.shyim.shopware6.util.PHPPattern.isShopwareStorefrontControllerTrans(PsiElement element) : boolean
          Class fr.adrienbrault.idea.symfony2plugin.Symfony2ProjectComponent is referenced in
            de.shyim.shopware6.completion.TwigCompletionProvider$4.addCompletions(CompletionParameters parameters, ProcessingContext context, CompletionResultSet result) : void
            de.shyim.shopware6.completion.TwigCompletionProvider$5.addCompletions(CompletionParameters parameters, ProcessingContext context, CompletionResultSet result) : void
            de.shyim.shopware6.completion.TwigCompletionProvider$6.addCompletions(CompletionParameters parameters, ProcessingContext context, CompletionResultSet result) : void
            de.shyim.shopware6.navigation.RouteGoToDeclareHandler.getGotoDeclarationTargets(PsiElement element, int offset, Editor editor) : PsiElement[]
          Class fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper is referenced in
            de.shyim.shopware6.completion.TwigCompletionProvider$4.addCompletions(CompletionParameters parameters, ProcessingContext context, CompletionResultSet result) : void
            de.shyim.shopware6.navigation.RouteGoToDeclareHandler.getGotoDeclarationTargets(PsiElement element, int offset, Editor editor) : PsiElement[]
          Class fr.adrienbrault.idea.symfony2plugin.extension.TranslatorProvider is referenced in
            de.shyim.shopware6.symfonyplugin.ShopwareTranslationProvider
        
```

**Comment by jankal** [comment]
@shyim the error about the `fr.adrienbrault.idea.symfony2plugin` plugin happened in the GitHub Actions since July so I just ignored it as it looks like we cannot do anything there.

I did not build the plugin with my changes, but I ran the tests - which worked.

**Comment by jankal** [comment]
@shyim build works here
image

**Comment by shyim** [comment]
I will look later more into, I think the plugin store upload will fail due to this

**Comment by jankal** [comment]
@shyim the Plugin store upload has failed since 0.0.43 - that's the latest version in the store.

**Pull request merged**
